services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - http.port=9200
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk-net
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    user: root
    command: ["-c", "/usr/share/filebeat/filebeat.yml", "-e"]
    restart: always
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./netflow.yml:/usr/share/filebeat/modules.d/netflow.yml:ro
    ports:
      - "2055:2055/udp"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200

volumes:
  esdata:

networks:
  elk-net:
    driver: bridge
